language: bash
env:
  - NEEDSOME_HOME=${PWD}/needsomelib PATH=${PATH}:${PWD}/needsomelib/need-some-init.bash/bin/
before_script:
  - mkdir needsomelib
  - mkdir needsomedown
  - git clone "https://github.com/need-some/need-some-init.bash.git" needsomedown/need-some-init.bash
  - git clone "https://github.com/need-some/need-some-test.bash.git" needsomedown/need-some-test.bash
  - mkdir needsomelib/need-some-init.bash && cp -a needsomedown/need-some-init.bash/src/* needsomelib/need-some-init.bash/
  - mkdir needsomelib/need-some-test.bash && cp -a needsomedown/need-some-test.bash/src/* needsomelib/need-some-test.bash/
script:
  - ./needsomelib/need-some-test.bash/bin/bashunit ./test

