language: bash
env:
  - NEEDSOME_HOME=./needsomelib PATH=./needsomelib/need-some-init.bash/src/bin/
before_script:
  - mkdir needsomelib
  - git clone "https://github.com/need-some/need-some-init.bash.git" needsomelib/need-some-init.bash
  - git clone "https://github.com/need-some/need-some-test.bash.git" needsomelib/need-some-test.bash
script:
  - ./needsomelib/need-some-test.bash/src/bin/bashunit ./test

